# Generated by Django 6.0.3 on 2026-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
