# Generated by Django 6.0.3 on 2026-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='box_only',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='college',
            field=models.CharField(choices=[('CAS', 'CAS'), ('CCS', 'CCS'), ('COE', 'COE'), ('CED', 'CED'), ('CIT', 'CIT'), ('CHTM', 'CHTM'), ('CBPA', 'CBPA'), ('CCJE', 'CCJE'), ('CAFA', 'CAFA')], default='CAS', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lent_to_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='office',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sealed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='serviceable',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unserviceable',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
