# Generated by Django 6.0.3 on 2026-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_serial_transaction_box_only_transaction_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='college',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='office',
        ),
        migrations.AddField(
            model_name='transaction',
            name='office_college',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
