# Generated by Django 6.0.3 on 2026-04-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_borrowrequest_transaction_returned_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_requests', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='transaction_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
