# Generated by Django 6.0.3 on 2026-04-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_borrowrequest_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_college', models.CharField(blank=True, max_length=255)),
                ('accountable_person', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(default='Tablet', max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('serviceable', models.BooleanField(default=False)),
                ('non_serviceable', models.BooleanField(default=False)),
                ('sealed', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=False)),
                ('incomplete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
