# Generated by Django 6.0.3 on 2026-04-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_devicemonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='display_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
