# Generated by Django 6.0.3 on 2026-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_devicemonitor_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='borrower_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='office',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='year_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
