# Generated by Django 6.0.3 on 2026-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_borrowrequest_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='office_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
