# Generated by Django 6.0.3 on 2026-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_borrowrequest_office_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number', max_length=100, null=True),
        ),
    ]
