# Generated by Django 6.0.3 on 2026-04-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transaction_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='accountable_officer',
            field=models.CharField(blank=True, help_text='Accountable Officer name', max_length=255),
        ),
    ]
