# Generated by Django 6.0.3 on 2026-04-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_devicemonitor_accountable_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='box_number',
            field=models.CharField(blank=True, help_text='Box number for the device', max_length=100),
        ),
    ]
