# Generated by Django 6.0.3 on 2026-04-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_devicemonitor_box_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemonitor',
            name='display_id',
        ),
    ]
