# Generated by Django 6.0.3 on 2026-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_devicemonitor_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='borrower_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicemonitor',
            name='accountable_officer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devicemonitor',
            name='box_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
