# Generated by Django 6.0.3 on 2026-04-20 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_devicemonitor_borrower_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemonitor',
            name='issue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devicemonitor',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number (comma-separated)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransactionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('box_number', models.CharField(blank=True, max_length=100)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
