# Generated by Django 6.0.3 on 2026-04-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_devicemonitor_date_returned_devicemonitor_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='transaction_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
