# Generated by Django 6.0.3 on 2026-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_devicemonitor_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
