# Generated by Django 6.0.3 on 2026-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_borrowrequest_section_borrowrequest_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='assigned_mr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assigned M.R.'),
        ),
        migrations.AddField(
            model_name='devicemonitor',
            name='ptr',
            field=models.CharField(blank=True, max_length=100, verbose_name='PTR'),
        ),
    ]
