# Generated by Django 6.0.3 on 2026-04-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_devicemonitor_assigned_mr_devicemonitor_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Marked as released (borrowed) via import'),
        ),
    ]
