# Generated by Django 6.0.3 on 2026-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_devicemonitor_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemonitor',
            name='is_released',
            field=models.BooleanField(default=False, help_text='True if device is currently borrowed/released'),
        ),
    ]
