# Generated by Django 6.0.3 on 2026-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='borrowrequest',
            name='inv_br_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='borrowrequest',
            name='inv_br_borrower_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='borrowrequest',
            name='inv_br_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemonitor',
            name='inv_dm_is_released_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemonitor',
            name='inv_dm_date_returned_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemonitor',
            name='inv_dm_office_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemonitor',
            name='inv_dm_box_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='inv_tx_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='inv_tx_borrowed_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='inv_tx_status_borrowed_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactiondevice',
            name='inv_td_serial_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactiondevice',
            name='inv_td_returned_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactiondevice',
            name='inv_td_tx_returned_idx',
        ),
        migrations.AddField(
            model_name='devicemonitor',
            name='release_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
